### ISSUE TITLE
Blocking - Linux master throws errors when module is present 

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/puppet-chocolatey#54]
When environment variables are not set, provider throws an error (happens on linux masters every time)

```
Error: Could not autoload puppet/provider/package/chocolatey: undefined method `+' for nil:NilClass
/var/lib/puppet/lib/puppet/provider/package/chocolatey.rb:24:in `chocolatey_command'
/var/lib/puppet/lib/puppet/provider/package/chocolatey.rb:69:in `block in <top (required)>'
```

Which corresponds to https://github.com/chocolatey/puppet-chocolatey/blob/master/lib/puppet/provider/package/chocolatey.rb#L24

**Comment by ferventcoder** [comment]
Workaround https://gist.github.com/ferventcoder/d5d9d9bb5c25548f24eb
